package cli

// Command-level usage. Per-command flag lists are generated by the flag package
// from the definitions themselves (see newFlagSet), so only the top-level
// overview is written by hand.

const rootUsage = `gocurlffi - HTTP with browser impersonation, and a pure-Go headless browser

usage:
  gocurlffi get <url> [flags]            fast HTTP client with browser TLS/JA3
  gocurlffi get <url> --render [flags]   load the URL in the pure-Go browser
  gocurlffi open <url> [flags]           shorthand for "get --render"
  gocurlffi serve [flags]                CDP + WebDriver BiDi server
  gocurlffi mcp [flags]                  MCP tool server (stdio, or --port for HTTP)
  gocurlffi targets                      list impersonation targets
  gocurlffi version                      print the version
  gocurlffi help [command]               this overview, or a command's flags

methods:
  get, post, put, patch, delete, head, options, trace
  A bare method is accepted as a command: "gocurlffi post <url> -d k=v".
  --render applies to get/fetch/open only; a request body has no browser path.

examples:
  gocurlffi get tls.browserleaks.com/json -i chrome150
  gocurlffi get example.com -H 'Accept-Language: en-GB' -v
  gocurlffi post httpbin.org/post -j '{"a":1}'
  gocurlffi get quotes.toscrape.com/js/ --render --format text

The fast path and the browser share one binary and one impersonation target.
"gocurlffi get" constructs no JavaScript engine; --render constructs one.

run "gocurlffi help <command>" for that command's flags.
`
