#!/usr/bin/env python3
"""Generate impersonate/presets_gen.go from impersonate/presets.json.

Run scripts/gen_presets.py first to (re)build the JSON from the vendored
curl-impersonate source. Then run this script and `gofmt`.

Usage: python3 scripts/gen_go.py
"""

from __future__ import annotations

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "impersonate", "presets.json")
OUT = os.path.join(ROOT, "impersonate", "presets_gen.go")

HEADER = """// Code generated by scripts/gen_go.py from impersonate/presets.json. DO NOT EDIT.
//
// Source: curl-impersonate lib/impersonate.c (MIT, see upstream/LICENSE.curl-impersonate).

package impersonate

var presets = []Preset{
"""


def gostr(s: str) -> str:
    out = ['"']
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20:
            out.append("\\x%02x" % ord(ch))
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def goslice(values) -> str:
    if not values:
        return "nil"
    return "[]string{" + ", ".join(gostr(v) for v in values) + "}"


def goheaders(values) -> str:
    if not values:
        return "nil"
    parts = []
    for line in values:
        name, _, value = line.partition(":")
        parts.append("{Name: %s, Value: %s}" % (gostr(name), gostr(value.lstrip())))
    return "[]Header{" + ", ".join(parts) + "}"


def split_colon(p, field) -> list[str]:
    v = p.get(field)
    if not v:
        return []
    return [x for x in v.split(":") if x]


def split_comma(p, field) -> list[str]:
    v = p.get(field)
    if not v:
        return []
    return [x for x in v.split(",") if x]


def render(p: dict) -> str:
    def b(field):
        return "true" if p.get(field) else "false"

    def i(field):
        return str(p.get(field) or 0)

    lines = ["  {"]
    lines.append("    Target: %s," % gostr(p["target"]))
    lines.append("    Alias: %s," % gostr(p.get("alias") or ""))
    lines.append("    HTTPVersion: %s," % i("httpversion"))
    lines.append("    SSLVersion: %s," % i("ssl_version"))
    lines.append("    Ciphers: %s," % goslice(split_colon(p, "ciphers")))
    lines.append("    Curves: %s," % goslice(split_colon(p, "curves")))
    lines.append("    HTTP3Curves: %s," % goslice(split_colon(p, "http3_curves")))
    lines.append("    SigHashAlgs: %s," % goslice(split_colon(p, "sig_hash_algs")))
    lines.append(
        "    HTTP3SigHashAlgs: %s," % goslice(split_colon(p, "http3_sig_hash_algs"))
    )
    lines.append("    NPN: %s," % b("npn"))
    lines.append("    ALPN: %s," % b("alpn"))
    lines.append("    ALPS: %s," % b("alps"))
    lines.append("    TLSSessionTicket: %s," % b("tls_session_ticket"))
    lines.append("    WSDisableSessionTicket: %s," % b("ws_disable_session_ticket"))
    lines.append(
        "    CertCompression: %s," % goslice(split_comma(p, "cert_compression"))
    )
    lines.append(
        "    WSCertCompression: %s," % goslice(split_comma(p, "ws_cert_compression"))
    )
    lines.append("    HTTPHeaders: %s," % goheaders(p.get("http_headers") or []))
    lines.append("    HTTP3Headers: %s," % goheaders(p.get("http3_headers") or []))
    lines.append("    WSHeaders: %s," % goheaders(p.get("ws_headers") or []))
    lines.append(
        "    HTTP2PseudoHeadersOrder: %s," % gostr(p.get("http2_pseudo_headers_order") or "")
    )
    lines.append("    HTTP2Settings: %s," % gostr(p.get("http2_settings") or ""))
    lines.append("    HTTPHeaderOrder: %s," % gostr(p.get("http_header_order") or ""))
    lines.append(
        "    HTTP3HTTPHeaderOrder: %s," % gostr(p.get("http3_http_header_order") or "")
    )
    lines.append(
        "    WSHTTPHeaderOrder: %s," % gostr(p.get("ws_http_header_order") or "")
    )
    lines.append("    HTTP2WindowUpdate: %s," % i("http2_window_update"))
    lines.append("    HTTP2Streams: %s," % gostr(p.get("http2_streams") or ""))
    lines.append(
        "    HTTP3PseudoHeadersOrder: %s,"
        % gostr(p.get("http3_pseudo_headers_order") or "")
    )
    lines.append("    HTTP3Settings: %s," % gostr(p.get("http3_settings") or ""))
    lines.append("    QUICCIDLength: %s," % gostr(p.get("quic_cid_length") or ""))
    lines.append(
        "    QUICTransportParameters: %s,"
        % gostr(p.get("quic_transport_parameters") or "")
    )
    lines.append("    TLSPermuteExtensions: %s," % b("tls_permute_extensions"))
    lines.append("    TLSUseNewALPSCodepoint: %s," % b("tls_use_new_alps_codepoint"))
    lines.append("    TLSSignedCertTimestamps: %s," % b("tls_signed_cert_timestamps"))
    lines.append("    TLSTrustAnchors: %s," % goslice(p.get("tls_trust_anchors") or []))
    lines.append("    ECH: %s," % gostr(p.get("ech") or ""))
    lines.append("    TLSExtensionOrder: %s," % gostr(p.get("tls_extension_order") or ""))
    lines.append(
        "    HTTP3TLSExtensionOrder: %s,"
        % gostr(p.get("http3_tls_extension_order") or "")
    )
    lines.append(
        "    TLSDelegatedCredentials: %s,"
        % goslice(split_colon(p, "tls_delegated_credentials"))
    )
    lines.append("    TLSRecordSizeLimit: %s," % i("tls_record_size_limit"))
    lines.append("    TLSKeySharesLimit: %s," % i("tls_key_shares_limit"))
    lines.append("    TLSGrease: %s," % b("tls_grease"))
    lines.append("    HTTP2StreamWeight: %s," % i("http2_stream_weight"))
    lines.append("    HTTP2StreamExclusive: %s," % i("http2_stream_exclusive"))
    lines.append("    HTTP2NoPriority: %s," % b("http2_no_priority"))
    lines.append("    ProxyCredentialNoReuse: %s," % b("proxy_credential_no_reuse"))
    lines.append("    SplitCookies: %s," % b("split_cookies"))
    lines.append("    FormBoundary: %s," % gostr(p.get("form_boundary") or ""))
    lines.append("  },")
    return "\n".join(lines)


def main() -> int:
    presets = json.load(open(SRC, encoding="utf-8"))
    # Stable ordering: keep source order but sort by target for determinism.
    presets.sort(key=lambda p: p["target"])
    body = "\n".join(render(p) for p in presets)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(HEADER)
        f.write(body)
        f.write("\n}\n")
    print(f"wrote {len(presets)} presets to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
